[package]
name = "asdi"
description = "Another Simplistic Datalog Implementation (in Rust)"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/johnstonskj/rust-asdi"
license-file = "LICENSE"

[features]
parser = ["pest", "pest_derive"]
tabular = ["prettytable-rs"]
typeset = []

[dependencies]
bimap = "0.6"

pest = { version = "2.1", optional = true }
pest_derive = { version = "2.1", optional = true }
prettytable-rs = { version = "0.8", optional = true }

[dev-dependencies]
pretty_assertions = "1.0"