[package]
name = "asdi"
description = "Another Simplistic Datalog Implementation (in Rust)"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/johnstonskj/rust-asdi"
license-file = "LICENSE"

[features]
default = ["parser", "tabular"]
parser = ["pest", "pest_derive"]
tabular = ["prettytable-rs"]
typeset = []

[dependencies]
tracing = "0.1.29"

pest = { version = "2.1", optional = true }
pest_derive = { version = "2.1", optional = true }
prettytable-rs = { version = "0.8", optional = true }

[dev-dependencies]
pretty_assertions = "1.0"
proptest = "1.0"

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "doc-src/header.html" ]