@startuml

!include ../model/options.plantuml

class asdi::Program #white
hide "asdi::Program" members

namespace asdi::visitor {

    interface Formatter

    interface ProgramVisitor<T> #white {
        start_program(program: &Program) -> Result<T>
        end_program(program: &Program) : Result<T>
        === ••• ==
    }

    Formatter --|> "<String>" ProgramVisitor

    class features << module >> {
        format_program(program: &Program, visitor: &impl Formatter) : String
        visit_program<T>(program: &Program, visitor: &impl ProgramVisitor<T>) : Result<T>
    }

    features ..> ProgramVisitor
    features ..> Formatter
}

@enduml