@startuml

!include options.plantuml

namespace asdi {

    namespace edb {
        namespace io {}
    }
    namespace error {}
    namespace features {}
    namespace idb {
        namespace eval {}
        namespace query {}
    }
    namespace parse {}
    namespace visitor {}
}

@enduml