name: mdbook to pages

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

defaults:
  run:
    shell: bash
    working-directory: ./book

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1.1.14
        with:
          mdbook-version: 'latest'

      - name: Build
        run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book